runtime: nodejs18

env_variables:
  DB_HOST: "34.128.104.8"
  DB_USER: "root"
  DB_PASSWORD: ""
  DB_NAME: "capstone_db"
  JWT_SECRET: "2115c30ffd99d39764fa50e8758ed0175443d6ca379374cbfbf52357e9872186cb3ab9623623b4b137494537e75f39043f11661a03edadfec40ce664e4d1a093"
  INSTANCE_CONNECTION_NAME: "capstone-stunting:asia-southeast2:stuntingcc"

beta_settings:
  cloud_sql_instances: "capstone-stunting:asia-southeast2:stuntingcc"
